language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="dns"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.02.3 DEPOPTS="tcpip lwt async" REVDEPS="true"
   - DISTRO=debian-testing OCAML_VERSION=4.02.3 DEPOPTS="tcpip lwt async"
   - DISTRO=debian-unstable OCAML_VERSION=4.02.3 DEPOPTS="tcpip lwt async"
   - DISTRO=ubuntu-12.04 OCAML_VERSION=4.01.0 DEPOPTS="tcpip lwt" REVDEPS="true"
   - DISTRO=ubuntu-15.10 OCAML_VERSION=4.02.3 DEPOPTS="tcpip lwt async"
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.02.3 DEPOPTS="tcpip lwt async"
   - DISTRO=centos-6 OCAML_VERSION=4.01.0 DEPOPTS="tcpip lwt"
   - DISTRO=centos-7 OCAML_VERSION=4.02.3 DEPOPTS="tcpip lwt async"
   - DISTRO=fedora-23 OCAML_VERSION=4.02.3 DEPOPTS="tcpip lwt async"
   - DISTRO=alpine-3.3 OCAML_VERSION=4.02.3 DEPOPTS="tcpip lwt"
